### ISSUE TITLE
ios版提示这个，您有办法解决吗？

### ISSUE THREAD

**Issue by GD2021** [luoweihz/sub-store-template#1]
![image](https://github.com/user-attachments/assets/45304294-bdd7-4bba-a36e-66257dea3081)

**Comment by luoweihz** [comment]
我的也有这个提示但是不影响使用

**Comment by luoweihz** [comment]
inet4_address 和 inet6_address 已合并为 address,修改这部分就不会有提示了
请参考: https://sing-box.sagernet.org/zh/migration/#tun
